# Generated by Django 5.1.3 on 2024-12-07 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='energydata',
            name='function',
        ),
    ]
