version: '3.8'
services:
  backend:
    container_name: smartfarm
    build:
      context: .
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    expose:
      - 8000
    depends_on:
      - my-postgres
    env_file:
      - .env
    networks:
      - mynetwork

  my-postgres:
    image: postgres
    container_name: database
    volumes:
      - psql-db:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
volumes:
  psql-db:
