# Provisioner Bearer Type Codes
PB_ADV    = 0x01
PB_GATT   = 0x02
PB_BEARER = 0x04

# Remote Provisioning Server Status Codes
REMOTE_PROVISIONER_STATUS_SUCCESS                                   = 0x00
REMOTE_PROVISIONER_STATUS_SCANNING_CANNOT_START                     = 0x01
REMOTE_PROVISIONER_STATUS_INVALID_STATE                             = 0x02
REMOTE_PROVISIONER_STATUS_LIMITED_RESOURCES                         = 0x03
REMOTE_PROVISIONER_STATUS_LINK_CANNOT_OPEN                          = 0x04
REMOTE_PROVISIONER_STATUS_LINK_OPEN_FAILED                          = 0x05
REMOTE_PROVISIONER_STATUS_LINK_CLOSED_BY_DEVICE                     = 0x06
REMOTE_PROVISIONER_STATUS_LINK_CLOSED_BY_SERVER                     = 0x07
REMOTE_PROVISIONER_STATUS_LINK_CLOSED_BY_CLIENT                     = 0x08
REMOTE_PROVISIONER_STATUS_LINK_CLOSED_AS_CANNOT_RECEIVE_PDU         = 0x09
REMOTE_PROVISIONER_STATUS_LINK_CLOSED_AS_CANNOT_SEND_PDU            = 0x0A
REMOTE_PROVISIONER_STATUS_LINK_CLOSED_AS_CANNOT_DELIVER_PDU_REPORT  = 0x0B

# Remote Provisioning Link Close Reason Field Values
REMOTE_PROVISIONING_LINK_CLOSE_REASON_SUCCESS           = 0x00
REMOTE_PROVISIONING_LINK_CLOSE_REASON_PROHIBITED        = 0x01
REMOTE_PROVISIONING_LINK_CLOSE_REASON_FAIL              = 0x02

# Remote Provisioning Link State Values
REMOTE_PROVISIONING_LINK_STATE_IDLE                     = 0x00
REMOTE_PROVISIONING_LINK_STATE_LINK_OPENING             = 0x01
REMOTE_PROVISIONING_LINK_STATE_LINK_ACTIVE              = 0x02
REMOTE_PROVISIONING_LINK_STATE_OUTBOUND_PACKET_TRANSFER = 0x03
REMOTE_PROVISIONING_LINK_STATE_LINK_CLOSING             = 0x04